spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cliente-endereco-solid-v1
    password:
    username:
    driverClassName: org.postgresql.Driver